spring.application.name=springsecurity
spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.datasource.username=root
spring.datasource.password=PasswordIsUsername
spring.datasource.url=jdbc:mysql://localhost:3306/spring_security

#This stops Spring Boot from treating the URL as a static resource request.
#spring.web.resources.add-mappings = false

#It will restart the application if it detects any changes
spring.devtools.restart.enabled = false


spring.security.user.name=root
spring.security.user.password=toor